version: "3.9"

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    container_name: ts-next-chat-sample-workspace
    tty: true
    volumes:
      - .:/work/ts-next-chat-sample
      - ts-next-chat-sample_node_modules_volume:/work/ts-next-chat-sample/node_modules
    working_dir: /work/ts-next-chat-sample
    ports:
      - 3001:3000

volumes:
  ts-next-chat-sample_node_modules_volume:
